### ISSUE TITLE
Base font issues

### ISSUE THREAD

**Issue by caffo** [c8r/lab#15]
I set the base font in the theme, but the exported components have no reference of it:

## Setting base font
![screen shot 2017-10-20 at 18 00 26](https://user-images.githubusercontent.com/456/31839614-99672430-b5c0-11e7-91e2-a8e69ec56bd4.png)

## Heading component

```
import styled from 'styled-components'
import { space, fontSize, width, color } from 'styled-system'

const Heading = styled('h1')([], props => ({}), space, fontSize, width, color)

Heading.defaultProps = {
  fontSize: 8,
  m: 0,
  fontWeight: 'bold'
}

export default Heading
``` 
## Result

![screen shot 2017-10-20 at 18 01 38](https://user-images.githubusercontent.com/456/31839640-c21556ea-b5c0-11e7-9642-b4c2dd039b3c.png)

Am I missing something?

**EDIT:**  I am using `ThemeProvider` from `styled-components`.

**Comment by caffo** [comment]
I'm in fact getting the theme info into the component, but for some reason, it's not rendering as expected:

![screen shot 2017-10-20 at 18 11 50](https://user-images.githubusercontent.com/456/31840031-54915bb2-b5c2-11e7-9b6a-78d1b2a862dd.png)

**Comment by johnotander** [comment]
This is actually a missing piece in our docs. I'll be sure to update that this weekend.

We recommend creating a `Font` component that wraps your app similarly to your `ThemeProvider`.

```jsx
<ThemeProvider theme={theme}>
  <Font>
    <App />
  </Font>
</ThemeProvider>
```

And in your component you can reference your `theme` props to set the style:

```js
{
  fontFamily: '${props.theme.fonts[0]}'
}
```

What the `Font` would typically look like (as the json representation):

```js
{
      "name": "Font",
      "type": "div",
      "props": {},
      "style": {
        "fontFamily": "${props.theme.fonts[0]}"
      },
      "examples": [
        "<Font>Hello</Font>"
      ],
      "system": []
    }
```

Hope this helps!

**Comment by caffo** [comment]
Thanks!
