### ISSUE TITLE
Style composed components

### ISSUE THREAD

**Issue by caffo** [c8r/lab#19]
What's the expected way to style composed components? I want to use flexbox inside this FilterBar, for example:

![screen shot 2017-11-02 at 19 22 16](https://user-images.githubusercontent.com/456/32351080-6708cdde-c003-11e7-9829-266ebec18e45.png)

**Comment by caffo** [comment]
@jxnblk @mrmrs hello :)

**Comment by bbenitez** [comment]
I'd add a `flex` property to the `FilterBarBackground` component, which is the one that contains your Text, Count, and Button components.
