### ISSUE TITLE
Support for multiple themes?

### ISSUE THREAD

**Issue by jcsmesquita** [c8r/lab#22]
I'm trying to find more information about whether there is support for multiple themes?
We're already using Rebass in a project where we use themes as a way to white-label our product. I was wondering whether with compositor lab it's possible to easily switch between different themes?

**Comment by jcsmesquita** [comment]
Awesome work btw :)

**Comment by jxnblk** [comment]
Thanks for the question! As of right now, the Lab app only supports one theme at a time, but this is a great idea for a feature we could add to the app in the future. As a work-around, you could duplicate folders and adjust the theme, but that wouldn't keep the components in sync.

**Comment by jcsmesquita** [comment]
Thanks Brent!
