### ISSUE TITLE
Creating a new project leads to a blank screen

### ISSUE THREAD

**Issue by webdesserts** [c8r/lab#24]
Hello, wanted to get started with compositor lab, but I ran into a blank screen after clicking **new project**. When I open up the devtools, I get this error:

<img width="1311" alt="screenshot 2017-11-26 11 45 22" src="https://user-images.githubusercontent.com/916253/33242763-57ee6b70-d29f-11e7-801a-ba689e8e9893.png">

The documentation makes it sound like `lab.json` is supposed to be generated by the app, but it looks like that's not happening for some reason.

version: 0.0.67

**Comment by webdesserts** [comment]
It looks like it's also looking for some non-existant node_modules

**Comment by jxnblk** [comment]
Thanks for reporting this bug! Creating a new project should work again in v0.0.69, but please let us know if you're still seeing the issue.

**Comment by mrmrs** [comment]
Closing as this bug has been fixed.
