### ISSUE TITLE
Using props to determine styles

### ISSUE THREAD

**Issue by fazouane-marouane** [c8r/lab#30]
Hi,

Is there a way to use props values to determine styles?
I would have expected the following to work `color: this.props.stuff? 'red': 'blue'`. But it doesn't.

Can you explain how would one can achieve such a thing? Thanks.

**Comment by mrmrs** [comment]
Hi @fazouane-marouane,

That concept does work, but you need some additional syntax.  Here is your example rewritten. Let me know if you have any additional questions!

```
color: '${ props.stuff? "red" : "blue" }'
```

**Comment by fazouane-marouane** [comment]
Thanks it works like a charm!
