### ISSUE TITLE
[Bug] Theme > Base Font > selection is missing fonts

### ISSUE THREAD

**Issue by mcoppola** [c8r/lab#31]
I've noticed that the`Base Font` selection field in the `Theme` view, does not include fonts defined in my system.  More specifically, all of my 'User' defined fonts in font-book are missing.

Is the selection being imported from a particular path?

Using 2015 MacbookPro, OSX 10.12.6.

Thanks for all the help!

**Comment by jxnblk** [comment]
The *Base Font* field is intended to be the font that would be set at the root of your application. Typically that means a web-safe system font or a webfont that would be loaded in. The list in the autocomplete has a few of those, but you should be able to type any valid CSS font-family value in the input.

For fonts installed locally on your computer, you can find the name for the font by selecting `View > Show Font Info` from the menu in Font Book – I *think* it's the same as the name shown in the list, but I might be wrong. Let me know if you still are unable to set the font to the one you want

**Comment by mcoppola** [comment]
Hey @jxnblk, thanks for the note here.  Via Font Book `view > show font info` provided the Family name, which did work for me. 

Appreciate the help and excited about the product!
-Matt
