### ISSUE TITLE
Unable to find license key in the purchase email

### ISSUE THREAD

**Issue by omargourari** [c8r/lab#35]
Hi,
I just bought a Lab subscription but I'm having an hard time finding license key on my email.
Can I ask you an hint on where to find it
I just have an invoice and a receipt number like these below

Example:
Invoice #XXXXXXX-XXXX
Receipt #XXXX-XXXX

**Comment by jjperezaguinaga** [comment]
Same here, seems that an additional email should've been sent but so far no dice 😞

**Comment by jjperezaguinaga** [comment]
Any support here @johno, @jxnblk, or @mrmrs ? ☺️

**Comment by jxnblk** [comment]
@jjperezaguinaga Sorry about that! We’ve been having some issues with our email service, but you should’ve just received an email from us with the license key. Please let us know if you haven’t received that or if you run into any other issues

**Comment by 0xjjpa** [comment]
Received license and everything went great, thanks!
