### ISSUE TITLE
Can't reference spacing from within style object

### ISSUE THREAD

**Issue by mattmarcello** [c8r/lab#5]
It would be nice to be able to reference the spacing values when styling components.  

Consider the below example.  

![image](https://user-images.githubusercontent.com/4753479/30868181-e406c8c4-a2ab-11e7-8132-24b61cd9b407.png)

![image](https://user-images.githubusercontent.com/4753479/30868238-08e07e6a-a2ac-11e7-957b-f755d9cfc301.png)

I'd like to be able to reference the third step in the spacing scale so that changes in the scale will propagate down to the component.  

Maybe a cheap solution would be to allow users to specify default props other than those set in the visual editor. 

```
# props 
{
  mr: 3,
  ml: 3,
}
```

**Comment by jxnblk** [comment]
Thanks for the suggestion! We're working on a better solution for using thematic values within the style object, but in version 0.0.49, you can set [styled-system](https://github.com/jxnblk/styled-system) props like in your example with `mr` and `ml`

**Comment by johnotander** [comment]
Hey @mattmarcello,

This feature is now supported in the latest versions of Lab. You can specify either default props and/or reference the theme as props in the styles.

Thanks for opening this issue!
